#+ endpoint: https://lod.globalbioticinteractions.org/query
#+ defaults:
#+   - hash: hash://sha256/1e2b7436fce1848f41698e5a9c193f311abaf0ee051bec1a2e48b5106d29524d

SELECT DISTINCT
  ?doi
  ?uuid 
  ?contentId
  ?archiveUrl 
  ?seenAt
  ?provenanceId
  ?activity
WHERE  
{
    BIND(?_hash_iri as ?contentId) 
    BIND(<hash://sha256/5b7fa37bf8b64e7c935c4ff3389e36f8dd162f0705410dd719fd089e1ea253cd> as ?provenanceId)

{
    SELECT ?doi ?seenAt ?archiveUrl ?uuid ?activity
WHERE {
  graph ?activity {
    ?_hash_iri <http://www.w3.org/ns/prov#qualifiedGeneration> ?activity .  
    ?activity <http://www.w3.org/ns/prov#used> ?archiveUrl .
    ?activity <http://www.w3.org/ns/prov#generatedAtTime> ?seenAt .
  }
  graph ?g1 {
   ?uuid <http://www.w3.org/ns/prov#hadMember> ?archiveUrl .
   ?uuid <http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso> ?doi .
   ?archiveUrl <http://purl.org/dc/elements/1.1/format> "application/dwca" .
  }

}
} 
UNION
{
    SELECT ?doi ?seenAt ?archiveUrl ?uuid ?activity
WHERE {
   ?_hash_iri <http://www.w3.org/ns/prov#qualifiedGeneration> ?activity . 
   ?activity <http://www.w3.org/ns/prov#used> ?archiveUrl .
   ?activity <http://www.w3.org/ns/prov#generatedAtTime> ?seenAt .
   ?uuid <http://www.w3.org/ns/prov#hadMember> ?archiveUrl . 
   ?uuid <http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso> ?doi .
   ?archiveUrl <http://purl.org/dc/elements/1.1/format> "application/dwca" .
}
} 
} ORDER BY DESC(?seenAt) LIMIT 2

