// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Preston Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= preston-zenodo(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

preston-zenodo - create/update associated Zenodo records

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*preston zenodo* [*--allow-empty-publication-date*] [*--disable-archive-discovery*]
               [*--explicit-license-only*] [*--new-version*] [*--no-cache*]
               [*--no-progress*] [*--restricted-access-only*]
               [*--update-metadata-only*] [*-a*=_<hashType>_] [*-d*=_<depth>_]
               [*--data-dir*=_<dataDir>_] [*--endpoint*=_<apiEndpoint>_] [*-l*=_<logMode>_]
               [*--license*=_<licenseRelations>_] [*-r*=_<provenanceAnchor>_]
               [*--tmp-dir*=_<tmpDir>_] [*--community*=_<communities>_]...
               [*--repos*=_<remotes>_[,_<remotes>_...]]...

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

create/update associated Zenodo records

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--algo, --hash-algorithm*=_<hashType>_::
  Hash algorithm used to generate primary content identifiers. Supported values: sha256, md5, sha1.

*--allow-empty-publication-date*::
  Zenodo accepts deposits with empty publication dates. On accepting a deposit without publication date, Zenodo sets the publication date to current date/time by default.

*--community, --communities*=_<communities>_::
  associated Zenodo communities

*-d*, *--depth*=_<depth>_::
  folder depth of data dir

*--data-dir*=_<dataDir>_::
  Location of local content cache

*--disable-archive-discovery*::
  Do not index all remote data archive content; instead, request entire data archive and only retrieve the requested content.

*--endpoint*=_<apiEndpoint>_::
  Zenodo api endpoint. Uses [ ZENODO_ENDPOINT] environment variable by default.

*--explicit-license-only*::
  only deposit records with explicit licenses: default license not allowed.

*-l*, *--log*=_<logMode>_::
  Log format. Supported values: tsv, nquads.

*--license, --licenses*=_<licenseRelations>_::
  contentid (e.g., sha256, md5) to resource that associates licenses for (alternate) identifiers: when provided, only deposits with identified licenses are published. The license relations are expected in rdf/nquads format: <some:id> <http://purl.org/dc/elements/1.1/license> <https://spdx.org/licenses/...> .
+
 For example:
+
 <urn:lsid:biodiversitylibrary.org:part:94849> <http://purl.org/dc/elements/1.1/license> <https://spdx.org/licenses/CC-BY-NC-SA-3.0> .

*--new-version*::
  deposit new version if a Zenodo deposit with matching identifiers already exists

*--no-cache, --disable-cache*::
  Disable local content cache

*--no-progress*::
  Disable progress monitor

*-r*, *--anchor, --provenance-root, --provenance-anchor*=_<provenanceAnchor>_::
  specify the provenance root/anchor of the command. By default, any available data graph will be traversed up to it's most recent additions. If the provenance root is set, only specified provenance signature and their origins are included in the scope.

*--repos, --remote, --remotes, --include, --repositories*=_<remotes>_[,_<remotes>_...]::
  Included repository dependencies (e.g., https://linker.bio/,https://softwareheritage.org,https://wikimedia.org,https://dataone.org,https://zenodo.org)

*--restricted-access-only*::
  always set [access_right] to [restricted]

*--tmp-dir*=_<tmpDir>_::
  Location of local tmp dir

*--update-metadata-only*::
  update metadata of existing record(s) only: if no associated record exists do nothing.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
