// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 0.11.4@4e49001ad65af30602be953079627a12f7a0809a
:manmanual: Preston Manual
:mansource: 0.11.4@4e49001ad65af30602be953079627a12f7a0809a
:man-linkstyle: pass:[blue R < >]
= preston(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

preston - a biodiversity dataset tracker

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*preston* [*-hV*] [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

a biodiversity dataset tracker

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-h*, *--help*::
  Show this help message and exit.

*-V*, *--version*::
  Print version information and exit.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:preston-cat.adoc[*cat*, *get*]::
  get content by their content id (or anchored alias)

xref:preston-ls.adoc[*ls*, *log*, *logs*]::
  Show biodiversity dataset provenance logs

xref:preston-cp.adoc[*cp*, *copyTo*, *export*]::
  Copy biodiversity dataset graph

xref:preston-clone.adoc[*clone*, *pull*]::
  Clone biodiversity dataset graph

xref:preston-track.adoc[*track*, *update*, *snapshot*]::
  track content at resource location(s) or from stdin

xref:preston-append.adoc[*append*, *handle*, *process*, *add*]::
  Offline (re-)processing of tracked biodiversity dataset graph using stdin

xref:preston-history.adoc[*history*, *origin*, *origins*, *prov*, *provenance*]::
  Show history/origins/provenance of biodiversity dataset graph

xref:preston-merge.adoc[*merge*, *join*, *use*, *import*]::
  Merges biodiversity dataset graphs

xref:preston-grep.adoc[*grep*, *match*, *findURLs*]::
  Uses Java-style regular expression (e.g., "Homo sapie.*") to find matching content in biodiversity dataset graph

xref:preston-test.adoc[*test*, *verify*, *check*, *validate*, *touch*]::
  Verifies completeness and, optionally, the integrity, of a biodiversity dataset graph by touching (or visiting) all associated content.

xref:preston-version.adoc[*version*]::
  Show version

xref:preston-seeds.adoc[*seeds*]::
  Lists supported biodiversity networks

xref:preston-hash.adoc[*hash*]::
  generate content id from stdin

xref:preston-alias.adoc[*alias*, *aliases*]::
  Define new (friendly) aliases, or names, for content hashes, or, when no definition is provided, lists related aliases instead.
+


xref:preston-dwc-stream.adoc[*dwc-stream*, *json-stream*, *dwc-json-stream*]::
  Extract records from DarwinCore archives in line-json

xref:preston-dbase-json-stream.adoc[*dbase-json-stream*, *dbase2json*, *dbase-stream*]::
  Extract records from DBase files (*.DBF) in line-json

xref:preston-excel-stream.adoc[*excel-stream*, *excel2json*, *xlsx-stream*, *xls-stream*]::
  Extract records from Excel files (*.xls, *.xlsx) in line-json

xref:preston-plazi-stream.adoc[*plazi-stream*]::
  transforms plazi treatment xml into json stream 

xref:preston-zenodo.adoc[*zenodo*, *publish*]::
  create/update associated Zenodo records

xref:preston-zotero-stream.adoc[*zotero-stream*]::
  Stream Zotero records into line-json with Zenodo metadata

xref:preston-zotero2ris.adoc[*zotero2ris*, *zotero-to-ris-stream*]::
  Stream Zotero records into RIS records

xref:preston-ris-stream.adoc[*ris-stream*]::
  translates bibliographic citations from RIS format into Zenodo metadata in JSON lines format

xref:preston-genbank-stream.adoc[*genbank-stream*, *gb-stream*]::
  Stream genbank accession records into line-json

xref:preston-taxodros-stream.adoc[*taxodros-stream*]::
  Stream TaxoDros https://www.taxodros.uzh.ch/ records into line-json with Zenodo metadata; Also see Bächli, G. (2024). TaxoDros - The Database on Taxonomy of Drosophilidae hash://md5/d68c923002c43271cee07ba172c67b0b hash://sha256/3e41eec4c91598b8a2de96e1d1ed47d271a7560eb6ef350a17bc67cc61255302 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10565403 .

xref:preston-mbd-stream.adoc[*mbd-stream*]::
  Stream Museum for Biological Diversity (MBD) Database Pages into line-json

xref:preston-github-stream.adoc[*github-stream*, *gh-stream*]::
  Stream GitHub metadata into line-json

xref:preston-taxonworks-stream.adoc[*taxonworks-stream*, *tw-stream*]::
  Stream TaxonWorks metadata into line-json

xref:preston-serve.adoc[*serve*, *s*, *server*]::
  provide access to content via http endpoint

xref:preston-redirect.adoc[*redirect*, *r*, *proxy*]::
  attempts to redirect to content associated with provided identifier in a defined content universe

xref:preston-cite.adoc[*cite*]::
  Cites datasets in dataset archive

xref:preston-qrcode.adoc[*qrcode*, *label*]::
  generates a printable PNG image QRCode of provenance head or anchor. See also "head".

xref:preston-head.adoc[*head*]::
  shows most recent provenance log version/hash

xref:preston-bash.adoc[*bash*]::
  runs provided bash script and tracks stdout

xref:preston-config-man.adoc[*config-man*, *config-manpage*, *install-manpage*]::
  Installs/configures Preston man page, so you can type [man preston] on unix-like system to learn more about Preston. 

xref:preston-gen-manpage.adoc[*gen-manpage*]::
  Generates man pages for all commands in the specified directory.

xref:preston-help.adoc[*help*]::
  Displays help information about the specified command

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
