// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Preston Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= preston-track(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

preston-track - track content at resource location(s) or from stdin

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*preston track* [*--disable-archive-discovery*] [*--no-cache*] [*--no-progress*]
              [*-a*=_<hashType>_] [*-d*=_<depth>_] [*--data-dir*=_<dataDir>_]
              [*-f*=_<filename>_] [*-l*=_<logMode>_] [*-r*=_<provenanceAnchor>_]
              [*--tmp-dir*=_<tmpDir>_] [*--repos*=_<remotes>_[,_<remotes>_...]]...
              [*-u*=_<seeds>_]... [*-m*=_<description>_...] [_<IRIs>_...]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Track content at some resource location (or url)

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--algo, --hash-algorithm*=_<hashType>_::
  Hash algorithm used to generate primary content identifiers. Supported values: sha256, md5, sha1.

*-d*, *--depth*=_<depth>_::
  folder depth of data dir

*--data-dir*=_<dataDir>_::
  Location of local content cache

*--disable-archive-discovery*::
  Do not index all remote data archive content; instead, request entire data archive and only retrieve the requested content.

*-f*, *--file*=_<filename>_::
  Read URLs to be tracked from file.

*-l*, *--log*=_<logMode>_::
  Log format. Supported values: tsv, nquads.

*-m*, *--message*=_<description>_...::
  Custom description of this tracking activity or command. (default: "A crawl event that discovers biodiversity archives.")

*--no-cache, --disable-cache*::
  Disable local content cache

*--no-progress*::
  Disable progress monitor

*-r*, *--anchor, --provenance-root, --provenance-anchor*=_<provenanceAnchor>_::
  specify the provenance root/anchor of the command. By default, any available data graph will be traversed up to it's most recent additions. If the provenance root is set, only specified provenance signature and their origins are included in the scope.

*--repos, --remote, --remotes, --include, --repositories*=_<remotes>_[,_<remotes>_...]::
  Included repository dependencies (e.g., https://linker.bio/,https://softwareheritage.org,https://wikimedia.org,https://dataone.org,https://zenodo.org)

*--tmp-dir*=_<tmpDir>_::
  Location of local tmp dir

*-u*, *--seed*=_<seeds>_::
  Starting points for graph discovery. Only active when no content urls are provided.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

[_<IRIs>_...]::
  [url1] [url2] ...

// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
== Examples

[%hardbreaks]

1.
Track a natural history collection at UC Santa Barbara UCSB-IZC via their GBIF Dataset DOI, then print their first record.
----
preston track\
 https://doi.org/10.15468/w6hvhv\
 | preston dwc-stream\
 | head -1\
 | jq .\
 > specimen.json
----

2.
Get a DwC-A file, track that DwC-A file via stdin, then print their first record into specimen.json.
----
preston cat\
 --remote https://softwareheritage.org\
 hash://sha256/856ecd48436bb220a80f0a746f94abd7c4ea47cb61d946286f7e25cf0ec69dc1\
 > dwca.zip
cat dwca.zip\
 | preston track\
 | preston dwc-stream\
 | head -1\
 | jq .\
 > specimen.json
----

3.
Track content locations in files, then print their first record.
----
echo https://en.wikipedia.org/wiki/Cat > urls.txt
echo https://en.wikipedia.org/wiki/Dog >> urls.txt
preston track -f urls.txt\
 | preston cat\
 > cat-and-dog.html
----

// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
